interface ActionTypes {
  ADD_PASSENGER: "ADD_PASSENGER";
  CHOOSE_DESTINATION: "CHOOSE_DESTINATION";
  CHOOSE_ORIGIN: "CHOOSE_ORIGIN";
  DELETE_PASSENGER: "DELETE_PASSENGER";
  EDIT_PASSENGER_NAME: "EDIT_PASSENGER_NAME";
  GOOGLE_API_LOADED: "GOOGLE_API_LOADED";
  SET_DIALOG_LOCATION: "SET_DIALOG_LOCATION";
  SET_PASSENGER_LOCATION: "SET_PASSENGER_LOCATION";
  TOGGLE_BOOKED: "TOGGLE_BOOKED";
  TOGGLE_DAYTIME: "TOGGLE_DAYTIME";
}

const actionTypes: ActionTypes = {
  ADD_PASSENGER: "ADD_PASSENGER",
  CHOOSE_DESTINATION: "CHOOSE_DESTINATION",
  CHOOSE_ORIGIN: "CHOOSE_ORIGIN",
  DELETE_PASSENGER: "DELETE_PASSENGER",
  EDIT_PASSENGER_NAME: "EDIT_PASSENGER_NAME",
  GOOGLE_API_LOADED: "GOOGLE_API_LOADED",
  SET_DIALOG_LOCATION: "SET_DIALOG_LOCATION",
  SET_PASSENGER_LOCATION: "SET_PASSENGER_LOCATION",
  TOGGLE_BOOKED: "TOGGLE_BOOKED",
  TOGGLE_DAYTIME: "TOGGLE_DAYTIME"
};

export default actionTypes;
