interface ActionTypes {
  ADD_PASSENGER: "ADD_PASSENGER";
  DELETE_PASSENGER: "DELETE_PASSENGER";
  EDIT_PASSENGER_NAME: "EDIT_PASSENGER_NAME";
  GOOGLE_API_LOADED: "GOOGLE_API_LOADED";
}

const actionTypes: ActionTypes = {
  ADD_PASSENGER: "ADD_PASSENGER",
  DELETE_PASSENGER: "DELETE_PASSENGER",
  EDIT_PASSENGER_NAME: "EDIT_PASSENGER_NAME",
  GOOGLE_API_LOADED: "GOOGLE_API_LOADED"
};

export default actionTypes;
